import nodemailer from "nodemailer";

interface SmtpConfig {
  host: string;
  port: number;
  secure: boolean;
  username: string;
  password: string; // Will be decrypted by the service before passing here
}

interface SendMailParams {
  from: string;
  to: string | string[];
  cc?: string | string[];
  bcc?: string | string[];
  subject: string;
  textBody: string;
  htmlBody?: string;
  inReplyTo?: string;
  references?: string[];
}

/**
 * Industry-standard SMTP Adapter.
 * Completely stateless. Connects, sends, and closes the connection.
 */
export async function sendViaSmtp(
  config: SmtpConfig,
  params: SendMailParams,
): Promise<string> {
  const transporter = nodemailer.createTransport({
    host: config.host,
    port: config.port,
    secure: config.secure,
    auth: {
      user: config.username,
      pass: config.password,
    },
  });

  const mailOptions = {
    from: params.from,
    to: params.to,
    cc: params.cc,
    bcc: params.bcc,
    subject: params.subject,
    text: params.textBody,
    html: params.htmlBody,
    inReplyTo: params.inReplyTo,
    references: params.references,
  };

  const info = await transporter.sendMail(mailOptions);

  // Return the unique Message-ID generated by the provider
  return info.messageId;
}
